### PR TITLE
Bump version to 1.0.2

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-fnv/6)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Ugh, I `cargo publish`ed 62f062b683b9131676354be0c1b8237454261897 instead of `6467ac398356a8cbdc7e10c7d6f651f9cbb563bd`

**Comment by Manishearth** [comment]
Okay, fix that, and r=me :smile:

**Comment by frewsxcv** [comment]
I meant that I just published v1.0.1 as a version that's not `HEAD`, which is why I opened this PR.

**Pull request merged**
